name = "FlexPlan"
uuid = "4dc3fedf-fcb4-4327-bce2-523fd266e8c9"
autors = ["Hakan Ergun", "Matteo Rossini", "Marco Rossi", "Damien Lapage", "Iver Bakken Sperstad", "Espen Flo Bødal", "Merkebu Zenebe Degefa", "Reinhilde D'hulst"]
repo = "https://github.com/electa-git/FlexPlan.jl"
version = "0.2.1"

[deps]
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PowerModelsACDC = "ff45984e-d068-5f4c-9e32-c4133509d236"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
CSV = "0.9, 0.10"
Cbc = ">= 0.9"
DataFrames = "^1"
InfrastructureModels = "~0.6, ~0.7"
Ipopt = ">= 0.8"
JSON = "~0.21.1"
JuMP = "~0.22.0"
Juniper = ">= 0.8"
MathOptInterface = "=0.10.9"
Memento = "~1.0, ~1.1, ~1.2, ~1.3"
PowerModels = "0.19.1"
PowerModelsACDC = "=0.5.2"
SCS = ">= 0.8"
julia = "1.5"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CSV", "Cbc", "DataFrames", "Ipopt", "Juniper", "SCS", "Test"]
