name = "FlexPlan"
uuid = "4dc3fedf-fcb4-4327-bce2-523fd266e8c9"
authors = ["Hakan Ergun", "Matteo Rossini", "Marco Rossi", "Damien Lepage", "Iver Bakken Sperstad", "Espen Flo Bødal", "Merkebu Zenebe Degefa", "Reinhilde D'Hulst"]
repo = "https://github.com/electa-git/FlexPlan.jl"
version = "0.3.0"

[deps]
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PowerModelsACDC = "ff45984e-d068-5f4c-9e32-c4133509d236"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
CSV = "0.10"
DataFrames = "1"
HiGHS = "0.3.2, 1"
InfrastructureModels = "0.6, 0.7"
JSON = "0.21.1"
JuMP = "0.22, 0.23, 1"
Memento = "1"
PowerModels = "0.19.6"
PowerModelsACDC = "0.6"
julia = "1.6"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CSV", "DataFrames", "HiGHS", "Test"]
